# Generated by Django 5.1.7 on 2025-03-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favsong',
            name='song_name',
            field=models.CharField(max_length=100),
        ),
    ]
